name: Watch Yaml Directory Changes

on:
  push:
    paths:
      - 'cfg/**/*.ini'
  workflow_dispatch:       # 允许手动触发

jobs:
  run-custom-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # 需要完整历史以进行合并

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Run customization script
        run: |
          bash .github/scripts/customize.sh

      - name: Run convert yaml script
        run: |
          bash .github/scripts/convert_yaml.sh

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto customize when cfg directory changes" || echo "No changes to commit"
          git push origin main

